### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by CGareau** [delahaye-4D/4D-powershell#1]
I have a syntax error with i execute "__test" :

Error when executing the method "powershell_run_script" at line number 39

The encoding is not supported

Error code: -10512 (4DRT)
The encoding is not supported
component: '4DRT'
task -5, name: 'P_1'

Error code: 8 (4DRT)
An Alphanumeric argument was expected.
component: '4DRT'
task -5, name: 'P_1'

**Comment by delahaye-4D** [comment]
Tu as quoi comme code_page ?

**Comment by CGareau** [comment]
Lorsque j’exécute la méthode « __test » j’ai cette erreur :

[A screenshot of a social media post  Description automatically generated]


[cid:imagee2b705.JPG@d0793aad.4db4ac23]
Cédric Gareau
Ingénieur Support & Service clients
Email : Cedric.Gareau@4d.com<mailto:Cedric.Gareau@4d.com>
Web :   www.4D.com<http://www.4D.com>

4D SAS
66 route de Sartrouville
Parc Les Erables - Bâtiment 4
78230 Le Pecq - France
Standard :      +33 1 30 53 92 00

**Comment by delahaye-4D** [comment]
Ce composant est fait pour fonctionner sur Windows !
